spring:
  application:
    name: benchmark
  datasource:
    url: ${POSTGRES_URL:jdbc:postgresql://localhost:5432/orpheum-benchmark}
    username: ${POSTGRES_USER:postgres}
    password: ${POSTGRES_PASSWORD:root}
    hikari:
      maximum-pool-size: 10
      minimum-idle: 2
      idle-timeout: 300000         # 5 min
      connection-timeout: 30000    # 30s
      max-lifetime: 1800000        # 30 min
  flyway:
    enabled: true

orpheum:
  benchmark:
    property-groups:
      2bed-equal-quality-gzira:
        title: 2 Bed Properties In Gzira Of Comparable Quality
        description: A group of competitors in the Gzira area having 2 beds and of comparable quality/amenities
        location: Gzira
        bedroom-count: 2
        finishing-level: HIGH
        amenities-level: MEDIUM
        has-view: false
        competitors:
          good-vibes:
            title: Steps from the Seafront - Good vibes only!
            url: https://www.airbnb.com.mt/rooms/1378332450577754619
          refined-elegance:
            title: Refined Elegance By The Sea
            url: https://www.airbnb.com.mt/rooms/1405209871580505002
          gabriel-apartment:
            title: Gabriel's - 2 bedroom Apartment by Solea
            url: https://www.airbnb.com.mt/rooms/1503474773108657194
